# -*- coding: utf-8 -*-
"""Movie_review_Model_Creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taFNhuTkx52yiyn9IO5Nq-YiBvaf465R
"""

import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords

data = pd.read_csv('Movie_Review.csv')

data.dropna(inplace=True)

data

data['sentiment'].value_counts()

def clean_review(review):
    str = ' '.join(word for word in review.split() if word.lower() not in stopwords.words('english'))
    return str

import nltk
nltk.download('stopwords')

data['text'] = data['text'].apply(clean_review)

#wordcloud

from wordcloud import WordCloud

#draw Wordcloud
reviews = ' '.join(word for word in data['text'][data['sentiment'] == 'neg'].astype(str))
wordcloud = WordCloud(height = 600,width =1000, max_font_size = 100)
plt.figure(figsize = (15,12))
plt.imshow(wordcloud.generate(reviews), interpolation='bilinear')
plt.axis('off')
plt.show()

reviews = ' '.join(word for word in data['text'][data['sentiment']== 'pos'].astype(str))
wordcloud = WordCloud(height = 600, width = 1000, max_font_size =100)
plt.figure(figsize=(15,12))
plt.imshow(wordcloud.generate(reviews), interpolation='bilinear')
plt.axis('off')
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=2500)

reviews = cv.fit_transform(data['text']).toarray()

data['sentiment'] = data['sentiment'].replace(['pos','neg'],[1,0])

data['sentiment'].value_counts()

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

from sklearn.model_selection import train_test_split

reviews_train, reviews_test, sent_train, sent_test = train_test_split(reviews, data['sentiment'], test_size=0.2)

model.fit(reviews_train,sent_train)

predict = model.predict(reviews_test)

from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay
cm = confusion_matrix(sent_test, predict, labels=model.classes_)
display = ConfusionMatrixDisplay(confusion_matrix = cm, display_labels=model.classes_)
display.plot()
plt.show()

import pickle as pk

pk.dump(model,open('model.pkl','wb'))

pk.dump(cv,open('scaler.pkl','wb'))

